---
title: "Ejercicio: Media y desviación estandar"
output:
  github_document:
    html_preview: false
---

## Problemas

Ahora que conoces sobre variables, funciones y vectores puedes realizar los dos siguientes retos.

**Problema 1.** Define una función que devuelve la media de cualquier vector numérico, según la siguiente formula:
$$\bar{x} = \frac1n \sum_{i=1}^n x_i$$
Donde:

- $\bar{x}$ es el simbolo de la media
- $n$ es la cantidad total de datos o la longitud del vector
- $\sum_{i=1}^n$ es la sumatoria de todos los elementos de $i$ a $n$
- $x_i$ es cada elemento de la serie de valores, cada elemento del vector identificado con su indice

En terminos simples, la fórmula solo dice:

- Suma cada uno de los elementos del vector
- Multiplicalo por 1 dividido por la longitud del vector, lo que es lo mismo que directamente dividirlo por su longitud

**Problema 2.** Define una función que devuelva la desviación estandar de cualquier vector, según la siguiente fórmula:

$$s = \sqrt\frac{\sum_i^n(x_i - \bar{x})^2}{n - 1}$$
Esta fórmula usa los mismos símbolos ya definidos en la fórmula de la media.

En terminos simples, la fórmula solo dice:
- Restar a cada elemento la media. Esto para ver cuánto se desvian de ella
- Elevar al cuadrado cada elemento
- Sumar los resultados de los elementos anteriores
- Dividirla entre la cantidad de datos menos uno
- Finalmente, extraer su raiz cuadrada

> Tip: ten en mente todas las funciones que necesitarás para tu propia función, incluyendo sumatoria, longitud de vectores, operador de potencias. Y necesitarás averiguar la función que sirva para extraer raíces cuadradas.

Cuando termines, comprueba que tu función da el mismo resultado que las funciones nativas de R: `mean()` y `sd()`.

Las soluciones están en el archivo [`033-ej-media-desviacion-solucion.Rmd`](033-ej-media-desviacion-solucion.Rmd).
